### ISSUE TITLE
pyqt 多线程更新ui线程的ui数据

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/zhihu-rss#17]
现在有俩要更新的qml里面的ui数据
1. 当add完一个noticer后，需要爬虫动态，爬虫速度比较慢，需要多线程，当爬完的时候更新ui线程的listview(俩个)  [在这](https://github.com/SimplyY/zhihu_rss/blob/master/src%2Fcontrol%2Fadd.py#L43)
2. 再爬虫的时候，我启动了一个dialog，来显示爬虫进度，但是后来发现，只有一个进程的话，ui线程完全就不能更新数据啊qaq  [在这](https://github.com/SimplyY/zhihu_rss/blob/master/src%2Fmodel%2Ffeeds_list.py#L108)

pyqt相关的英文文档翻了好多，或许是我看不懂qaq

**Comment by SimplyY** [comment]
@xen0n 

help

气体菊苣快救我，我这俩合起来花的时间至少超过两天了qaq还没解决qaq

**Comment by xen0n** [comment]
UI操作只能在UI线程进行啊... 得实现线程间通信才行, 我没仔细看, 先把你的包结构调整了再研究这个

**Comment by SimplyY** [comment]
已解决通过在爬虫线程里给 ui 线程发信号即可
