### ISSUE TITLE
运行即报错，无法更新关注者状态·

### ISSUE THREAD

**Issue by nujeh** [SimplyY/zhihu-rss#28]
<img width="1201" alt="screen shot 2016-02-20 at 15 00 38" src="https://cloud.githubusercontent.com/assets/6964284/13195077/e19898fa-d7e2-11e5-92a0-b998b2efc983.png">

**Comment by SimplyY** [comment]
我这里没报错，非常推荐你先，pip3 install zhihu-py3 --upgrade，然后再运行一下 zhihu-py3 ，如果它报错，我的肯定也会出错。

如果它没有错了，zhihurss 还报错，再在这里说一下

**Comment by SimplyY** [comment]
这么久没反馈，应该已经解决了=。=

**Comment by nujeh** [comment]
没。。。。。

**Comment by SimplyY** [comment]
,我昨天用了还是好的，你是osx吗，还有zhihupy3测试成功了吗，

**Comment by SimplyY** [comment]
不知道你的 pyqt5是不是最新版，不是的话，看这里 https://github.com/SimplyY/zhihu-rss/issues/29

**Comment by nujeh** [comment]
PyQt5是装的最新版本，zhihupy3也测试成功了的，嗯，先等等吧，我解决了会在这发一下

**Comment by SimplyY** [comment]
那我就不知道了= =
